//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// GameEditorTestVer0.rc에서 사용되고 있습니다.
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_GameEditorTestVer0TYPE      130
#define ID_WINDOW_MANAGER               131
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define IDR_PASTE_MENU                  151
#define ID_SORTPROPERTIES               151
#define IDR_WINDOWS_MENU                152
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDR_RIBBON                      307
#define IDD_LandscapeParentDlg          312
#define IDD_LandscapeManagementFormView 313
#define IDD_LandscapeSculptingFormView  314
#define ID_LANDSCAPE_DOCKPANE           315
#define IDI_FILE_SAVE                   316
#define ID_COMBO_EDITOR_MODE            317
#define IDB_FILE_SAVE                   318
#define IDD_NewProjectDlg               319
#define ID_OBJECT_SELECTOR_DOCKPANE     320
#define IDD_ObjectSelectorDlg           321
#define IDD_LandscapeSplattingFormView  323
#define ID_STATICMESH_LIST_BOX          410
#define IDB_FBX_SELECT                  411
#define IDC_COMBO_SECTION               412
#define ID_EDIT_COMP_WIDTH              413
#define ID_EDIT_COMP_HEIGHT             414
#define IDB_BTN_BUILD_LANDSCAPE         415
#define ID_OutlinerDockPane             1000
#define IDD_OutlinerParentDlg           1001
#define ID_OutlinerTreeView             1002
#define IDC_OUTLINER_TREE               1006
#define IDC_FBX_FILE_LIST               1007
#define IDC_BUTTON1                     1008
#define IDC_LANDSCAPE_MANAGEMENT        1008
#define IDC_BUTTON_DIRECTIONAL_LIGHT    1008
#define IDC_BTN_CREATE_LANDSCAPE        1008
#define IDC_LANDSCAPE_SCULPTING         1009
#define IDC_LANDSCAPE_PAINTING          1010
#define ID_DetailDockPane               1011
#define IDC_DETAIL_TREE                 1012
#define IDC_LIST1                       1013
#define IDC_LIST_OBJECT_SELECTOR        1013
#define IDC_EDIT1                       1014
#define IDC_EDIT2                       1015
#define IDC_BUTTON_SPOT_LIGHT           1016
#define IDC_BUTTON3                     1017
#define IDC_BUTTON_POINT_LIGHT          1017
#define IDC_LandscapeBaseTexture        1018
#define IDC_LandscapeLayer1             1019
#define IDC_LandscapeLayer2             1020
#define IDC_LandscapeLayer3             1021
#define IDC_LandscapeLayer4             1022
#define IDC_LayerSelectCombo            1024
#define IDC_BUTTON_SELECT_OBJECT        1025
#define IDC_BUTTON_ADD_OBJECT           1026
#define IDC_LANDSCAPE_COMPONENT_WIDTH   1028
#define IDC_LANDSCAPE_COMPONENT_HEIGHT  1029
#define IDC_COMBO1                      1030
#define IDC_COMBO_LANDSCAPE_SECTION_SIZE 1030
#define ID_WRITE_PASTEASHYPERLINK       32770

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        321
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           324
#endif
#endif
